### ISSUE TITLE
list valid filter operators in readme

### ISSUE THREAD

**Issue by fickse** [pivotbio/bulk-api-python-client#159]
For starters, this API is awesome -- thanks for building and documenting it so well!

Apologies if I missed this somewhere, but is there a list of valid operators for the filter argument in `model.query()`?

I see startswith, or, and, =, gte. Are there more?

In particular, is there a 'does not equal' operator? Some queries e.g. on the measurements table return a lot of rows without relevant data. It would be helpful to filter these on the server side before clogging bandwidth and disk space in transferring the response.

**Comment by LuapRebel** [comment]
@fickse I just noticed this issue was unresolved. The information is located here:
https://docs.djangoproject.com/en/3.2/ref/models/querysets/#field-lookups
and is linked to under the Queries section in the documentation.
