### ISSUE TITLE
The cache file path is hardcoded such that two or more users cannot run a client at the same time on a single machine.

### ISSUE THREAD

**Issue by paulraine** [pivotbio/bulk-api-python-client#188]
https://github.com/pivotbio/bulk-api-python-client/blob/release/bulk_api_client/client.py#L69-L71

For example I was trying to run a dash up on a machine that's in Berkley that @fickse was using to run his own dash app.

**Comment by glassresistor** [comment]
Is the issue the the files permissions don't allow r/w for both users?  Otherwise you should just be sharing a cache.

**Comment by paulraine** [comment]
I think it's just a r/w issue. This is on a linux machine.

**Comment by glassresistor** [comment]
These issues are public.  Maybe slack team directly.
